# Generated by Django 4.0 on 2022-06-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=30, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract Base', 'Contract Base')], max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'Job',
            },
        ),
    ]
